### ISSUE TITLE
Chain Merchant

### ISSUE THREAD

**Issue by r2net** [imzers/doku-whmcs#1]
what is a Chain Merchant?
I did not find the information in DOKU.

thank you for providing the module

**Comment by imzers** [comment]
As described by DOKU, you can use NA as Chainmerchant

On 9/16/17, Rudy <notifications@github.com> wrote:
> what is a Chain Merchant?
> I did not find the information in DOKU.
>
> thank you for providing the module
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/imzers/doku-whmcs/issues/1


-- 
Best regards,
Imran Nababan

**Comment by r2net** [comment]
Chain Merchant Name: NA
results https://staging.doku.com/Suite/Receive (redirect blank page)
but if I leave it blank Chain Merchant Name
error message:
"You have invalid payment request.
Description : invalid CHAINMERCHANT
Please try again or contact the Merchant"

Environment Mode Sandbox
thank you for your response

**Comment by imzers** [comment]
Hi r2net, for Chainmerchant you should ask DOKU about your merchant credential, is it allowed using NA as chainmerchant or another chainmerchant credential.
Could you post your Request to DOKU while make a payment? Thx

**Comment by r2net** [comment]
chainmerchant: NA (blank page)
chainmerchant: I empty (error message: invalid CHAINMERCHANT)

Can you help me? to create a module doku myshortcart (specify the cost), may be able to continue via email

**Comment by imzers** [comment]
Hi...
This module is not for DOKU Myshortcart, thats why you get this
error,This module is for DOKU Hosted as now as DOKU One Checkout

On 9/17/17, Rudy <notifications@github.com> wrote:
> chainmerchant: NA (blank page)
> chainmerchant: I empty (error message: invalid CHAINMERCHANT)
>
> Can you help me? to create a module doku myshortcart (specify the cost), may
> be able to continue via email
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/imzers/doku-whmcs/issues/1#issuecomment-330023671


-- 
Best regards,
Imran Nababan

**Comment by r2net** [comment]
Hallo,
doku.com (business) redirect to doku myshortcart. to my knowledge myshortcart is panel DOKU.

please check email for follow-up,
thank you

**Comment by r2net** [comment]
solved issues, there is no problem with the script, but this module is for DOKU Hosted. as described imzers, Sorry
